# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dbb809de7a69986aeff6a7a889dbc83e9feb48a121a6616e6798ee20f4fdaac70a1eafcecee7b9378ea7d99b2820fcaaf8c913b06c8876bff14f76062748d93

test:
  secret_key_base: 983b18879b773f1ecc62390fd1f1abe5d40ef9be2b280a0b90e663f33c6ba775bc47ee668ee8dc1b282d3d9bdb463c666d0cfc6f99ade5928e35d58fef557423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
